name: craftableinvframes
version: 2.2.2.2
api-version: 1.13
main: com.spiritothawk.plugins.craftableinvframes.CraftableInvFrames
authors: [Techdoodle, SpiritOTHawk, Timoti11]
commands:
  iframe:
    permission: craftableinvframes.cmd
    description: Gives the player an invisible item frame
    usage: /iframe
permissions:
  craftableinvframes.place:
    default: true
  craftableinvframes.craft:
    default: true
  craftableinvframes.cmd:
    default: op
  craftableinvframes.reload:
    default: op
  craftableinvframes.forcerecheck:
    default: op
  craftableinvframes.get:
    default: op
  craftableinvframes.give:
    default: op
  craftableinvframes.setitem.around:
    default: op
  craftableinvframes.setitem.center:
    default: op
